[package]
name = "galgebra"
version = "0.1.1"
edition = "2021"
description = "A library with geometric algebra stuff (vectors)"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rstest = "0.15.0"
